# Site settings
baseurl = "https://fishroe2019.ca/"
languageCode = "en-us"
title = "Brandy & Matt"

# Enter your tracking code to enable Google analytics
googleAnalytics = ""

[params]
  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # Countdown timer for a certain date. In this case, for our wedding ceremony!
  countdown = "August 17, 2019 14:30:00"
  # Human-readable format of the same date above
  countdownHuman = "Saturday, August 17th, 2019 at 2:30PM PDT"

  [params.logo]
    image = "assets/img/cobie.jpg"
    alt = "Engagement Photo"
    width = "80%"

  # Header section
  [params.header]
    title = "Brandy and Matt are getting married!"
